### ISSUE TITLE
move this repo to "Dual-Life" organization

### ISSUE THREAD

**Issue by rjbs** [Dual-Life/Time-Piece#30]
I'm not really involved in this dist anymore.  I would like to move it to the Dual-Life organization, which is used for dual life dists generally.  Any objections, @smith153?

**Comment by smith153** [comment]
That is fine with me. Though I don't know what exactly that entails. I looked at the Dual-Life org a year ago or so, but no one was using it then.

**Comment by rjbs** [comment]
I've asked Leon T. about helping me get this done.

**Comment by smith153** [comment]
No problem. Not sure what the whole process would be. I am hoping to push out a new stable version next week sometime. I can update the repo link in the Makefile.PL then.

**Comment by smith153** [comment]
Looks like we're good. Shall I close?

**Comment by rjbs** [comment]
Great, yes!  Actually, I will.  I was just waiting until you were in the organization  :)
