### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by quliping** [Dual-Life/Time-Piece#43]
The details of the error are as follows：
![qq 20180719152153](https://user-images.githubusercontent.com/39583607/42927598-8b427288-8b67-11e8-92ea-4a12e3a33f6c.png)

what's the problem?

**Comment by smith153** [comment]
Hard to say with such little info. I'm not really sure how you are trying to install Time::Piece either, looks like you are trying to install it for the local user (instead of system wide) but you are doing it into some custom source tree. The "Detected uninstalled Perl" line is interesting too...

 I'd recommend you subscribe to the beginners mailing list at: https://lists.perl.org/list/beginners.html and send an email to that with a subject of "Help installing module" or something similar. There are many knowledgeable people on there (as well as myself), and it would be a better method to get installation help.

**Comment by quliping** [comment]
actually I created a new folder named CORE and the problem was solved. Even I don't know why. But know I have another problem.
sfn114_WH@fncn01:~/software/source/perl/module/perl_module/Time-Piece-1.3204> make
"/home-fn/users/nsfn114_WH/software/source/perl/perl-5.26.2/perl" "-I/home-fn/users/nsfn114_WH/software/source/perl/perl-5.26.2/lib" -MExtUtils::Command::MM -e 'cp_nonempty' -- Piece.bs blib/arch/auto/Time/Piece/Piece.bs 644
"/home-fn/users/nsfn114_WH/software/source/perl/perl-5.26.2/perl" "-I/home-fn/users/nsfn114_WH/software/source/perl/perl-5.26.2/lib" "/home-fn/users/nsfn114_WH/software/source/perl/perl-5.26.2/lib/ExtUtils/xsubpp"  -typemap '/home-fn/users/nsfn114_WH/software/source/perl/perl-5.26.2/lib/ExtUtils/typemap'  Piece.xs > Piece.xsc
**Failed to load or import from ExtUtils::ParseXS (version 3.34). Please check that ExtUtils::ParseXS is installed correctly and that the newest version will be found in your @INC path: Can't locate loadable object for module re in @INC** (@INC contains: /home-fn/users/nsfn114_WH/software/source/perl/perl-5.26.2/lib /home-fn/users/nsfn114_WH/software/source/perl/perl-5.26.2/ext/re /home-fn/users/nsfn114_WH/software/source/perl/perl-5.26.2/install/lib/site_perl/5.26.2/x86_64-linux /home-fn/users/nsfn114_WH/software/source/perl/perl-5.26.2/install/lib/site_perl/5.26.2 /home-fn/users/nsfn114_WH/software/source/perl/perl-5.26.2/install/lib/5.26.2/x86_64-linux /home-fn/users/nsfn114_WH/software/source/perl/perl-5.26.2/install/lib/5.26.2) at /home-fn/users/nsfn114_WH/software/source/perl/perl-5.26.2/lib/ExtUtils/ParseXS.pm line 375.
Compilation failed in require at /home-fn/users/nsfn114_WH/software/source/perl/perl-5.26.2/lib/ExtUtils/ParseXS.pm line 375.
BEGIN failed--compilation aborted at /home-fn/users/nsfn114_WH/software/source/perl/perl-5.26.2/lib/ExtUtils/ParseXS.pm line 375.
Compilation failed in require at /home-fn/users/nsfn114_WH/software/source/perl/perl-5.26.2/lib/ExtUtils/xsubpp line 6.
make: *** [Piece.c] Error 255

But I've already installed this module: ExtUtils::ParseXS (version 3.34). And I find the re module under this directory: /home-fn/users/nsfn114_WH/software/source/perl/perl-5.26.2/ext/re. And I tried to install this re module but I saw the same error.

**Comment by mla** [comment]
@quliping those appear to be issues related to your Perl set up. Normally you'd use something like "cpanm" to handle module installations.

It looks like your module search path is probably screwed up or something.

There's nothing specific to Time::Piece here, AFAICT. Looks like you need general help with your Perl config, as @smith153 suggested.
